### ISSUE TITLE
Lua error on opening crafting table

### ISSUE THREAD

**Issue by filliph** [AcidWeb/RECraft#1]
After a `/reload`, I received the following error when I attempted to right click the profession crafting table:
```
1x RECraft/RECraft.lua:121: attempt to index field 'professionInfo' (a nil value)
[string "@RECraft/RECraft.lua"]:121: in function `OnEvent'
[string "*RECraft.xml:8_OnEvent"]:1: in function <[string "*RECraft.xml:8_OnEvent"]:1>
```
When this error occurred, it was not possible to open the crafting UI at all, either via the crafting table or the profession action button.

Additional info:
- RECraft was _not_ scanning when I reloaded the UI.
- I could not replicate the issue after another `/reload` - potentially I tried to open the profession UI too soon after `/reload`? I was parked right next to the crafting table

**Comment by AcidWeb** [comment]
It looks like there is some scenario where crafting table is not fully initialized. I will add some code that handle this case.
