### ISSUE TITLE
"Only first crafts and skill ups" doesn't work

### ISSUE THREAD

**Issue by filliph** [AcidWeb/RECraft#2]
At least for my Engineer, this feature flat out doesn't work. 

![image](https://user-images.githubusercontent.com/9424286/211121284-f1576ed2-cd75-4a05-85a4-1be5552ecf2f.png)

This still notifies for a public order for:

![image](https://user-images.githubusercontent.com/9424286/211121691-76b6a9dd-a0d8-4ad5-8e89-06662994207d.png)
![image](https://user-images.githubusercontent.com/9424286/211121706-92ecae62-5d69-4a48-9a1b-d2c89b6b65dc.png)

**Comment by AcidWeb** [comment]
This issue occur on a regular basis or was it an isolated incident? As not much can break in this logic.

**Comment by AcidWeb** [comment]
Found the source of the issue.
