### ISSUE TITLE
not working since 10.0.5

### ISSUE THREAD

**Issue by hollo6** [AcidWeb/RECraft#4]
Since 10.0.5 has gone live, nothing fires the notification.
Every filter option disabled (not only first craft, 0 smallest tip).
Nothing even gets parsed, I've been watching the orders for some time and there were definitely new ones posted, yet no notification and Parsed number remains 0 even when there are 100+ active orders and a lot of new ones being posted while running the search.

**Comment by AcidWeb** [comment]
Can't replicate it - used it this morning.

But I will take a look. Is search spinner is spinning?

**Comment by hollo6** [comment]
Thanks! Let me know if I can provide some logs or any other useful info.

**Comment by AcidWeb** [comment]
Considering the entire order system is failing today I would not be surprised this is some kind of anomaly.

https://www.reddit.com/r/woweconomy/comments/10kmyvu/problems_with_public_orders/

**Comment by hollo6** [comment]
I don't have any problems fulfilling orders, did several of them already but I have to refresh manually because still nothing gets parsed. :(
Couldn't it be because of the new order grouping system? (You have to go through 2 steps before being able to actually craft the orders, first selecting the list of orders for the same item then selecting the actual order from that list.)

**Comment by hollo6** [comment]
Looks like the issue is indeed related to the new grouping stuff.
Just tested with Alchemy and it works with that. But nothing is parsed for Inscription.

**Comment by AcidWeb** [comment]
Yes. It is caused by bucket mode that require completely different method of parsing. I'm working on it.

**Comment by hollo6** [comment]
Aaand it's working! You are awesome, thank you!

**Comment by sanyex89** [comment]
well its working for me for blacksmithing and alchemy but not jewelcrafting

**Comment by hollo6** [comment]
I just tested it with Jewelcrafting and it works.

**Comment by sanyex89** [comment]
![grafik](https://user-images.githubusercontent.com/77323774/214909736-ce3991f1-dead-4b5e-9810-de4984fe1727.png)
no swirly for me. just on jewelcrafting. blacksmith + alchemy works fine

**Comment by sanyex89** [comment]
![grafik](https://user-images.githubusercontent.com/77323774/214909930-48dc7de3-e270-4f57-b0c2-4c9feacd006c.png)
on alchemy

**Comment by AcidWeb** [comment]
Show me full jewelcrafting window.

**Comment by sanyex89** [comment]
![grafik](https://user-images.githubusercontent.com/77323774/214946492-6f42b4ed-398d-46e3-9b19-0d8d36e62f87.png)
is it because of the 0 orders remaining?

**Comment by AcidWeb** [comment]
Yes. When there is no orders remaining and guild scan is disabled too there is no reason to loop the search.

**Comment by sanyex89** [comment]
makes sense, thanks for your work and sorry for my stupidity
