### ISSUE TITLE
Request: add option to always show first crafts and ignore recipe learned state

### ISSUE THREAD

**Issue by hollo6** [AcidWeb/RECraft#5]
Could you please add an option to always show first crafts and/or skillups, regardless of tip amount?
E.g. I want orders to show up when the tip is >1000g OR they are a first craft, even if the tip is lower than that.

Also, it would be good to have an option to not check GetOrderViability.
For example, if there is an order for an item that I currently don't have the recipe for but I can purchase it to fill that order.

**Comment by AcidWeb** [comment]
Not sure if I want to open pandora box of fully customizable search. I will think about it.

**Comment by hollo6** [comment]
Thanks, I hope you will find this reasonable, for me this was the most logical setup and it's become a bit hard to change it every time after updating the addon, especially now when the options are getting more numerous and complicated.

Also, the option to only find orders with all reagents provided seems to be not working, it alerts on partially supplied orders too.
(Should I open a new ticket about this?)

**Comment by AcidWeb** [comment]
It is working for LW. Filter is using API output directly - no processing on addon level. If it is catching too much that mean game say that order have all mandatory reagents supplied.

**Comment by hollo6** [comment]
Oh then I think it's a misunderstanding about wording. Is there something that can be done on addon level to filter orders with all actual reagents supplied, not only all mandatory?

**Comment by hollo6** [comment]
Nevermind that claim about requiring all reagents not being considered, turns out I was missing some logic when editing the function.
Which just further reinforces my belief that these should be built-in options so people wanting to use it this way wouldn't just not have to edit it after every update but not mess it up either. :)

**Comment by hollo6** [comment]
I can't see this in the new version ?

**Comment by AcidWeb** [comment]
I don't plan to add it for now - sorry.
