### ISSUE TITLE
Patron order window issues

### ISSUE THREAD

**Issue by Luntho** [AcidWeb/RECraft#8]
![image](https://github.com/user-attachments/assets/cead2e8a-638f-4561-9bca-39aae2794b59)
![image](https://github.com/user-attachments/assets/ad09d794-686c-4016-aed5-3b99ab7d925e)

Having issues with patron orders not showing or being out of order. Also when moving window patron orders don't move with the window when recraft is enabled.

LUA Error:
Message: Attempted to release inactive object 'nil'
Time: Tue Sep  3 21:01:20 2024
Count: 6
Stack: Attempted to release inactive object 'nil'
[string "@Interface/AddOns/Blizzard_SharedXMLBase/Pools.lua"]:79: in function <Interface/AddOns/Blizzard_SharedXMLBase/Pools.lua:68>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/TableBuilder.lua"]:89: in function `RemoveRow'
[string "@Interface/AddOns/Blizzard_SharedXML/TableBuilder.lua"]:351: in function `RemoveRow'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollUtil.lua"]:1564: in function <...dOns/Blizzard_SharedXML/Shared/Scroll/ScrollUtil.lua:1563>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...e/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:672: in function <...ddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua:671>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...e/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua:143>
...
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:317: in function `SignalDataChangeEvent'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:297: in function `SetDataProvider'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:637: in function `SetDataProvider'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:673: in function <...Professions/Blizzard_ProfessionsCrafterOrderPage.lua:665>
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowGeneric'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:736: in function `ShowOrders'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:749: in function `OrderRequestCallback'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:636: in function <...Professions/Blizzard_ProfessionsCrafterOrderPage.lua:636>

Locals: self = <table> {
 activeObjects = <table> {
 }
 proxy = <table> {
 }
 activeObjectCount = <table> {
 }
 capacity = Infinite
 inactiveObjects = <table> {
 }
}
object = nil
canFailToFindObject = nil
active = false

**Comment by AcidWeb** [comment]
Duplicate #6
