### ISSUE TITLE
v1.5.0 LUA error on patron orders tab

### ISSUE THREAD

**Issue by hollo6** [AcidWeb/RECraft#9]
With this version, I get the following LUA error popup (even though I have BugSack set to suppress popups):

Message: Attempted to release inactive object 'nil'
Time: Fri Sep  6 10:17:25 2024
Count: 30
Stack: Attempted to release inactive object 'nil'
[string "@Interface/AddOns/Blizzard_SharedXMLBase/Pools.lua"]:79: in function <Interface/AddOns/Blizzard_SharedXMLBase/Pools.lua:68>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/TableBuilder.lua"]:89: in function `RemoveRow'
[string "@Interface/AddOns/Blizzard_SharedXML/TableBuilder.lua"]:351: in function `RemoveRow'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollUtil.lua"]:1564: in function <...dOns/Blizzard_SharedXML/Shared/Scroll/ScrollUtil.lua:1563>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...e/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:672: in function <...ddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua:671>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...e/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua:143>
...
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:317: in function `SignalDataChangeEvent'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:297: in function `SetDataProvider'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:637: in function `SetDataProvider'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:673: in function <...Professions/Blizzard_ProfessionsCrafterOrderPage.lua:665>
[string "=[C]"]: in function `ShowGeneric'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:736: in function `ShowOrders'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:749: in function `OrderRequestCallback'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:636: in function <...Professions/Blizzard_ProfessionsCrafterOrderPage.lua:636>

Locals: self = <table> {
 activeObjects = <table> {
 }
 proxy = <table> {
 }
 activeObjectCount = <table> {
 }
 capacity = Infinite
 inactiveObjects = <table> {
 }
}
object = nil
canFailToFindObject = nil
active = false

Preceded by:
3x RECraft/RECraft.lua:183: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@RECraft/RECraft.lua"]:183: in function `Populate'
[string "@Blizzard_SharedXML/TableBuilder.lua"]:102: in function `ConstructCell'
[string "@Blizzard_SharedXML/TableBuilder.lua"]:306: in function `Arrange'
[string "@RECraft/RECraft.lua"]:265: in function <RECraft/RECraft.lua:259>
[string "=[C]"]: in function `SetupTable'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:587: in function `SetCraftingOrderType'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:145: in function <...Professions/Blizzard_ProfessionsCrafterOrderPage.lua:143>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

I did not get this error in previous versions.

**Comment by AcidWeb** [comment]
Replace lua file inside addon directory with file inside this archive: [RECraft.zip](https://github.com/user-attachments/files/16905613/RECraft.zip)

If it works show me screenshot of your patron orders.

**Comment by hollo6** [comment]
Yeah I tried to do the same thing :) Got rid of the error but then the rewards column does not show up (not even on reopening the frame or switching tabs).

![image](https://github.com/user-attachments/assets/c8f41291-f14e-4c33-a82d-63bd29c0fc0b)

**Comment by AcidWeb** [comment]
Both columns are missing. Addon load at all?

**Comment by hollo6** [comment]
Oops sorry, I just made a typo on the second try.
I don't fully understand why but this guard works, mine was only a nilcheck.
All good with this one 👍

**Comment by AcidWeb** [comment]
Please test my code and provide screenshoot.

**Comment by hollo6** [comment]
What I'm trying to say is it works with yours, this fixed it.

**Comment by AcidWeb** [comment]
And I still wait for that screenshot.

**Comment by hollo6** [comment]
![image](https://github.com/user-attachments/assets/5912ea1a-a429-480d-a306-a59976fd6d8a)

**Comment by AcidWeb** [comment]
Strange. But if it works... Thanks for report.

**Comment by hollo6** [comment]
Agreed :) Thanks for the quick fix!
